-- Migration: wire live fetchers to existing tables
-- All three fetchers (sentiment, business-stats, marketing) now write into
-- the existing tables that rebuild_market_payload already reads from:
--   sentiment-feed.js   → intel_sentiment_items
--   business-stats-feed → intel_business_stats
--   marketing-feed.js   → intel_marketing_items_archive
--
-- No new tables are needed. This file is kept as a migration record only.
-- The intel_business_stats table already has the right structure (from schema.sql).
-- The intel_sentiment_items table already has the right structure (from schema.sql).
-- The intel_marketing_items_archive table already has the right structure (from schema.sql).
--
-- Only action: ensure RLS allows anon read (already set in schema.sql, this is idempotent).

-- (no-op if policies already exist — safe to re-run)
